= Auth Service

== Description
A rest microservice to authenticate a user against a valid running keycloak server configured according to application needs

== Supported Login Proviers
1. Native - basic email/password combo
2. Google oAuth
3. Apple oAuth
4. Facebook oAuth

== Pre-requisites
1. Properly configured https://www.keycloak.org/guides#getting-started[keycloak server]
2. Java 8+
3. Sbt

=== Configuring keycloak server for use
The keycloak server can be installed in the kubernetes cluster via a helm chart. However, there are some things that require careful configuration that are described below

==== 1. Install keycloak in k8s cluster via helm chart
1. `helm install auth-keycloak codecentric/keycloak --version 18.1.1`
2. Once pods are running and healthy, deploy ingress definitions to access keycloak server via application hostname
* {empty}
+
[source,yaml]
----
include::./deployment/minikube/keycloak-ingress.yaml[]
----
3. **Enable proxy address forwarding for keycloak** - this is required to serve redirect URLs via HTTPS (Apple auth fails otherwise!). For more info, https://github.com/codecentric/helm-charts/tree/master/charts/keycloak#running-keycloak-behind-a-reverse-proxy[refer to the docs here]
    - We do this via a helm upgrade, since we brought our keycloak deployment in via a helm chart
    - `touch extra-config.yaml`
    - Dump the following contents into `extra-config.yaml`
* {empty}
+
[source, zsh]
----
extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
    value: "true
----
    - `helm upgrade --reuse-values -f extra-config.yaml auth-keycloak codecentric/keycloak`


==== 2. Add Apple provider dependency to keycloak's list of identity providers
1. Apple as a provider is not natively supported by keycloak yet. However, https://github.com/BenjaminFavre/keycloak-apple-social-identity-provider[the open source community is here to rescue us!] - Unfortunately, we have to install this manually on each pod of the `Deployment/StatefulSet` in order for it to work
    - For a comprehensive guide, refer to https://github.com/ChathuminaVimukthi/Keycloak-with-Apple-Signin[this github post]
2. `kubectl get pods | grep keycloak`
3. `kubectl exec -it pod/<pod_name> bash`
4. `cd /opt/jboss/keycloak/standalone/deployments`
5. `curl -LO https://github.com/BenjaminFavre/keycloak-apple-social-identity-provider/releases/download/v1.0.2/apple-social-identity-provider-1.0.2.jar`
6. For a comprehensive guide on configuring Apple sign in details, https://github.com/ChathuminaVimukthi/Keycloak-with-Apple-Signin#keycloak[refer to this link]
    - Note - Apple sign in (and push notifications) requires a paid Apple developer subscription

==== Configure keycloak realms with right providers
1. Create 4 realms while logged into the keycloak admin console as admin
    - `NativeAuth`
    - `GoogleAuth`
    - `AppleAuth`
    - `FacebookAuth`
2. For each of these realms, to go `Configure` -> `Clients` and create 2 new clients
    - `webapp`
    - `mobileapp`
3. For **every client** (2 * 4 = 8 clients), go to `client` -> `Mappers` and create the following token mappers
    - `client_id` -> `User Session Note`
    - `user_id` -> `User Attribute`
    - `auth_realm` -> `User Attribute`
4. For `webapp` clients on **all 4 realms**, navigate to `Settings` -> `Web Origins` and add
    - `http://localhost:5555` - this is for local flutter web app development
    - any other domains that may be requesting resources - this is to avoid CORS errors
5. The following instructions are only for `mobileapp` and `webapp` clients for **oAuth Providers** - AppleAuth, FacebookAuth and GoogleAuth
    - For `webapp` clients on all 3 realms, add the following values for valid redirect URIs, where `<provider>` is one of `apple`, `google` or `facebook`
        - `http://api.vid.app/api/auth/<provider>/callback/webapp`
        - `http://localhost:5555/auth.html`
        - `http://localhost:9000/api/auth/<provider>/callback/webapp`
    - For `mobileapp` clients on all 3 realms, add the following valid redirect URI
        - `io.fitcentive.fitcentive://oidc-callback`
    - For all clients, adjust token expiry time as desired
6. For the oAuth realms (AppleAuth, FacebookAuth, GoogleAuth), go to `Configure` -> Identity Providers` and create the appropriate identity provider
    - Update keycloak openId settings as provided by the auth provider itself
7. For all realms, update the IDP's `First broken login` to `First broker login 3.0`
    - If `First broker login 3.0` does not exist, create it in the `Configure` -> `Authentication`
    - It should contain the following executions
        - `Create User If Unique` -> `Alternative`
        - `Automatically Set Existing User` -> `Alternative`
8. For all **oAuth realms**, go to `Confgure` -> `Identity Providers` -> `realm_name` -> `Mappers` and add the following mappers
    - `First Name, force, Attribute Importer, given_name, firstName`
    - `Last Name, force, Attribute Importer, family_name, lastName`
9. Alternatively, import settings into realms from exported JSON files

== Running service locally
1. This service has a dependency on the `user-service`. Either run that locally as well, or use `kubectl` port forwarding to make it available
    - `kubectl port-forward svc/user-service 9001:9000`
2. This service also needs access to a keycloak server running on port 8080
    - `kubectl port-forward svc/auth-keycloak-http 8080:80`
3. `sbt clean run`
4. `curl http://localhost:9000/api/auth/health` to bootstrap the server

== Deploy to minikube cluster

'''

=== Pre-requisites
Note - these pre-requisites need only be done **once ever**. If you are deploying another service and you have already followed these steps, no need to repeat them

==== 1. Start a single node `minikube` cluter with enough resources
1. `minikube -p=hyperkit --memory 8192 --cpus 8 start`
2.  **Note** - use the `hyperkit` driver otherwise TLS will not work

==== 2. Enable TLS on minikube cluster
1. `mkcert "*.vid.app"`
2. `kubectl -n kube-system create secret tls mkcert --key key.pem --cert cert.pem`
3. `minikube addons configure ingress`
4. Verify that certificate was enabled
    - `kubectl -n ingress-nginx get deployment ingress-nginx-controller -o yaml | grep "kube-system"`
5. For a comprehensive set of instructions, https://minikube.sigs.k8s.io/docs/tutorials/custom_cert_ingress/[refer to the minikube docs]

==== 3. Add DNS entry to local hosts file
1. `sudo vi /etc/hosts`
2. Add the following entry to the file below `127.0.0.1     localhost`
    - `192.168.64.3 api.vid.app`

'''

=== 1. Delete existing deployment and build fresh image
1. `kubectl delete deployment/auth-service`
2. `docker image ls | grep auth`
3. `docker image rm auth`
4. `docker image rm <image_hash>`
5. `sbt docker:publishLocal`


=== 2. Deploy manifests to minikube
1. Ensure you are on the right `kubectl` context
2. `cd deployment`
3. `kubectl apply -f minikube/`

=== 3. Verify working of server
1. `curl http://api.vid.app/api/auth/health`
    - Should return a `200` with response `Server is alive!`

==== Note
1. The generated SSL certificate might need explicit trusting by you on your browser for the first time
2. For the certificate to be accepted on Android or iOS devices, you have to import the certificate into the device and trust it manually
    - For Android or iOS, copy the `rootCA.pem` or `rootCA.der` file generated in step 1 into the device filesystem. Then, follow device specific instructions to trust the certificate
    - One might require conversion of `.pem` to `.der` or vice versa - make sure you use the right format (conversion is easy via a quick search)
    - `openssl x509 -inform PEM -outform DER -in rootCA.pem -out rootCA.der`



