apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: auth
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: gcr.io/fitcentive-dev/auth:1.0
          resources:
            requests:
              memory: 300Mi
              cpu: "0.3"
            limits:
              memory: 500Mi
              cpu: "0.5"
          ports:
            - name: http-port
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /api/auth/health
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/auth/health
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 15
          envFrom:
            - secretRef:
                name: internal-service-secret
          env:
            - name: USER_SERVICE_HOST
              value: "http://user-service"
            - name: USER_SERVICE_PORT
              value: "9000"
            - name: HTTP_SERVER_HOST
              value: "http://auth.fitcentive.xyz"
            - name: HTTP_SERVER_PORT
              value: "9000"
            - name: JWT_ISSUER
              value: "https://auth.fitcentive.xyz"
            - name: KEYCLOAK_EXTERNAL_SERVER_URL
              value: "http://auth.fitcentive.xyz/auth"
            - name: KEYCLOAK_INTERNAL_SERVER_URL
              value: "http://keycloak-service-http/auth"
